### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by valkyrienyanko** [jsferrarelli/prudent-tial#2]
Can you add some pictures or videos showing off what you have done so far please?

**Comment by jsatof** [comment]
Hi there, sure thing. I just want to let you know, this project just started so all I'm doing right now is making the base game.

I'll put up a readme later today or tomorrow

**Comment by jsatof** [comment]
Put up the readme with screenshots. dae2684dbbb190065fce75b8ec99490f471f72ee
